Adding rollback in ci.yml

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -45,13 +45,86 @@ jobs:
      uses: actions/upload-pages-artifact@v3
      with:
       path: dist/demo/browser
+#  deploy:
+#   needs: build
+#   runs-on: ubuntu-latest
+#   environment:
+#    name: github-pages
+#    url: ${{ steps.deployment.outputs.page_url }}
+#   steps:
+#    - name: Deploy to GitHub Pages
+#      id: deployment
+#      uses: actions/deploy-pages@v4
  deploy:
-  needs: build
-  runs-on: ubuntu-latest
-  environment:
-   name: github-pages
-   url: ${{ steps.deployment.outputs.page_url }}
-  steps:
-   - name: Deploy to GitHub Pages
-     id: deployment
-     uses: actions/deploy-pages@v4
+    needs: build
+    runs-on: ubuntu-latest
+    environment:
+      name: github-pages
+    steps:
+      - name: Deploy to GitHub Pages
+        id: deployment
+        uses: actions/deploy-pages@v4
+
+      - name: Wait before health check
+        run: sleep 20
+
+      - name: Health check
+        id: health
+        run: |
+          STATUS=$(curl -s -o /dev/null -w "%{http_code}" ${{ steps.deployment.outputs.page_url }})
+          echo "HTTP STATUS: $STATUS"
+          if [ "$STATUS" != "200" ]; then
+            echo "Health check failed"
+            exit 1
+          fi
+ rollback:
+    needs: deploy
+    if: failure()
+    runs-on: ubuntu-latest
+    steps:
+      - name: Check if stable tag exists
+        id: check_stable
+        run: |
+          if git ls-remote --tags origin stable | grep stable; then
+            echo "stable_exists=true" >> $GITHUB_OUTPUT
+          else
+            echo "stable_exists=false" >> $GITHUB_OUTPUT
+          fi
+      - name: Stop if no stable version
+        if: steps.check_stable.outputs.stable_exists == 'false'
+        run: |
+          echo "No stable version found. Cannot rollback."
+          exit 0
+
+      - name: Checkout stable version
+        if: steps.check_stable.outputs.stable_exists == 'true'
+        uses: actions/checkout@v3
+        with:
+          ref: stable
+
+      - name: Setup Node.js
+        if: steps.check_stable.outputs.stable_exists == 'true'
+        uses: actions/setup-node@v3
+        with:
+          node-version: 20
+
+      - name: Install dependencies
+        if: steps.check_stable.outputs.stable_exists == 'true'
+        run: npm install
+    
+      - name: adding environment variables
+        if: steps.check_stable.outputs.stable_exists == 'true'
+        run: |
+          mkdir -p src/environments
+          cat <<EOF > src/environments/environment.prod.ts
+          export const environment = {
+            production: true,
+            supabaseUrl: "${{ vars.VITE_SUPABASE_URL }}",
+            supabaseAnonKey: "${{ vars.VITE_SUPABASE_ANON_KEY }}"
+          };
+          EOF
+
+      - name: Rebuild stable version
+        if: steps.check_stable.outputs.stable_exists == 'true'
+        run: npm run build -- --base-href="/${{ github.event.repository.name }}/"
+          --configuration production
